### ISSUE TITLE
"Print Article as PDF" isn´t available in Article Syndication (C4.9)

### ISSUE THREAD

**Issue by w3scout** [w3scout/contao-dompdf-bundle#3]

**Comment by zonky2** [comment]
sure? works fine under Contao 4.4.9
https://easycaptures.com/fs/uploaded/1518/6714460155.png
with https://github.com/w3scout/contao-dompdf-bundle/pull/4

**Comment by max-admina** [comment]
We can confirm problems with Contao 4.9 (not Contao 4.4.9).

The Checkbox isn't showing in Contao 4.9.9 and also not in Contao 4.9.10.
It works if "contao/tcpdf-bundle" is installed and in the system settings DOM PDF is activated. But the **@print-CSS** parameter are not fully supported.

Example:
```
@media print {
    body {display: none !important;}
}
```

This will cause a clean white page for printing. With legacy printing method this works fine, but when exporting pdf, only some css instructions are taken into account. This in any case not, even if you leave @media print and nothing will display, the generated pdf will show the whole contend.

In older Contao versions it worked. Since the upgrade to 4.9.x, these instructions no longer work. Only an installation of the "contao/tcpdf-bundle" extension showed the required checkbox again.

Presumably, the checkbox is still not displayed and "contao/tcpdf-bundle" will control the PDF output instead. However, when DOM PDF is uninstalled, CSS is no longer taken into account when outputting the CSS.
